### ISSUE TITLE
Move from Surface to pure LiveView

### ISSUE THREAD

**Issue by tmjoen** [brandocms/brando#1253]
## Functionality we need
- [x] Slots in Live Components (currently only in function components)
- [x] Slots in function components
- [x] JS Commands
- [x] heex
- [x] Event targeting
- [ ] Declare props (just comment out surface props for now)

## Todo
- [x] Unify form input component API
- [x] Update `brando.gen` templates (create/update/list)
- [x] Setup `use BrandoAdmin, :live_view/:live_component`
- [x] `use Surface.LiveView` -> `use BrandoAdmin, :live_view`
- [x] `use Surface.Component` -> `use Phoenix.Component`
- [x] `use Surface.LiveComponent` -> `use BrandoAdmin, :live_component`
- [x] Get rid of `<Context>`
- [x] Move `Inputs`, `MapInputs`, `ArrayInputs` to func comps under `Form`
- [x] Ensure all `render_slot` yields maps not kwlists
- [x] Ensure all components that use slots pull out from maps instead of kwlists
- [x] Convert `~F` templates to heex `~H`
  - [x] Go through ALL `:on-click`. A regular Surface click = `phx-click={JS.push("refresh_jobs", target: @myself)}`
  - [x] Interpolation outside of tags: `{@test}` -> `<%= @test %>`
  - [x] Dynamic components must be called with function: `<Input.Text.render>`
  - [x] `:let` -> `let`
  - [x] Keyword lists must be wrapped in `[]` -> `let={[form: f, index: idx]}`

## Obstacles
- [x] Dynamically call function components
```elixir
def render(assigns) do
  if is_live?(@component_module) do
    ~F"""
    <div class="brando-input">
        <.live_component module={@component_module}
          id: @component_id,
          form: @form,
          field: @field,
          label: @label,
          placeholder: @placeholder,
          instructions: @instructions,
          uploads: @uploads,
          opts: @opts,
          current_user: @current_user
        />
    """
  else
    apply(component_module, :render, ...)
  end
end
```
