### ISSUE TITLE
Rewrite Villain — too slow with large data in LV

### ISSUE THREAD

**Issue by tmjoen** [brandocms/brando#1668]
## Approach 1 — Keep Villain outside of LV

- set up a channel per villain
- `phx-update="ignore"` each villain
- diff on block basis

## Approach 2 — Split blocks into individual base forms

- split the blocks array into forms for each "base" block.
- stitch the base block forms together

### TODO
- [x] Don't render `:blocks` input as part of regular `form`
  - [x] deprecate `input :<name>, :blocks`
  - [x] introduce `blocks :<name>, {opts}`
- [ ] `stitch_blocks` > store in form component state?
- [ ] Create a generated `blocks_changeset` that will validate the stitched together blocks
- [x] Don't validate `__villain_fields__` in the regular changeset

- Every MODULE block has its own form
- phx_change each form and stitch it in on change by UID
- Module block should have a ref to its parent container UID (if any)

**Comment by tmjoen** [comment]
Can the containers have a form that does not wrap it's children?

```
<container>
  <form>
     ...
  </form>
  <!-- block renderer for its children here? -->
</container>
```

**Comment by tmjoen** [comment]
continued in #2109
